# Generated by Django 6.0.3 on 2026-03-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneldecontrol', '0002_usuario_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_text', models.CharField(max_length=350)),
                ('tienecosas', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paneldecontrol.usuario')),
            ],
        ),
    ]
