# Generated by Django 6.0.3 on 2026-03-17 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneldecontrol', '0003_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
