# Generated by Django 6.0.3 on 2026-03-28 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneldecontrol', '0005_categoria_marca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='inventario_text',
            new_name='nombreproducto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='id',
        ),
        migrations.AddField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(default=0, max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
