# Generated by Django 6.0.3 on 2026-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneldecontrol', '0006_rename_inventario_text_inventario_nombreproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(default=1, max_length=6, primary_key=True, serialize=False),
        ),
    ]
