# Generated by Django 6.0.3 on 2026-03-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneldecontrol', '0007_alter_inventario_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='codigo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
         migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paneldecontrol.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='marca',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paneldecontrol.marca'),
            preserve_default=False,
        ),
    ]
