# Generated by Django 6.0.3 on 2026-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneldecontrol', '0009_remove_inventario_id_inventario_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='codigo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
