# Generated by Django 6.0.3 on 2026-03-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneldecontrol', '0010_remove_inventario_codigo_inventario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='id',
        ),
        migrations.AddField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(default=1, max_length=6, primary_key=True, serialize=False),
        ),
    ]
